name: Deploy to ECR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.CS415_AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CS415_AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.CS415_AWS_SESSION_TOKEN }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cs415-ecr-api
        IMAGE_TAG: latest
        ECS_CLUSTER: cs415-ecs-cluster-api
        FARGATE_SERVICE: cs415-api-fargate-service
        REGION: us-west-2
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        aws ecs update-service --cluster $ECS_CLUSTER --service $FARGATE_SERVICE --force-new-deployment --region $REGION